# Configuration du build Netlify
[build]
  # Commande pour installer les dépendances
  command = "npm install"
  # Aucun dossier de publication car Express ne génère pas de fichiers statiques
  publish = "."

# Définition du dossier où Netlify trouve les fonctions serverless
[functions]
  directory = "netlify/functions"
  included_files = ["route/**", "bd/connect.js", "controller/**", "middleware/**", "netlify/functions/api.js"]

# Variables d'environnement pour la production
[context.production.environment]
  DB_HOST = "srv1514.hstgr.io"
  DB_USER = "u249205154_topzen"
  DB_PASSWORD = "Topzen2025@"
  DB_NAME = "u249205154_topzen"
  FRONTEND_URL = "https://front-fgczxnzr4-ldjhds-projects.vercel.app/"
