[build]
  command = "npm install"
  publish = "public"  # Si tu as un dossier public avec des fichiers statiques à déployer

[functions]
  directory = "netlify/functions"  # Dossier où tu stockes tes fonctions

[context.production.environment]
  DB_HOST = "http://www.aldipeong.org/"
  DB_USER = "weziza_aldipetest"
  DB_PASSWORD = "zPYLfABSt987Bmyr3bpt"
  DB_NAME = "weziza_aldipetest"
  FRONTEND_URL = "https://front-fgczxnzr4-ldjhds-projects.vercel.app/"
  SENDGRID_API_KEY = "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"
  SENDGRID_EMAIL = "contacttoconnect2022@gmail.com"
