name: Deploy Backend

on:
  push:
    branches:
      - master  # Déclenche le déploiement lors d'un push sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choisir la version de Node.js

      - name: Install dependencies
        run: |
          npm install
      
      - name: Deploy to Server
        run: |
          # Exemple de commande pour déployer sur un serveur via SSH (ajoute ta propre logique)
          ssh user@hostname 'cd /path/to/your/app && git pull && npm install && pm2 restart app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
